### PR TITLE
GUI

### PR DESCRIPTION
**Pull request by james58899**
# API
* GUI
  * Builder
    * Set title
    * Binding slot
  * Thread safe inventory editor
  * Binding click event
  * Open/Close listener
* GUI Back Stack Manager
  * Open GUI
  * Close all GUI

# Block
* GUI test block

# Fix
* Clone custom block

### CODE REVIEW

**Review by bill96012 — APPROVED** [review]
Test passed

**Review by jimchen5209 — APPROVED** [review]
## Review Passed

**Review by bill96012 — COMMENTED** [review]
1. 面對方塊並蹲下時依然被禁止使用某些物品
    https://streamable.com/8f96rz

**Review by bill96012 — APPROVED** [review]
Test passed

**Pull request merged**
